### ISSUE TITLE
SMTPConfiguration causing Compilation error

### ISSUE THREAD

**Issue by aekazitt** [playframework/play-mailer#77]
package mail
    
    import javax.inject.Provider
    
    import play.api.libs.SMTPConfiguration
    import play.api.{Configuration, Environment}
    import play.api.inject.Module
    
    class TestMailerConfigurationProvider extends Provider[SMTPConfiguration] {
        override def get() = new SMTPConfiguration("http://192.168.9.2", 25)
    }
    
    class TestMailerConfigurationModule extends Module {
        def bindings(environment: Environment, configuration: Configuration) = Seq(
            bind[SMTPConfiguration].toProvider[TestConfigurationProvider]
        )
    }

Hi, I'm pretty new to Scala here so pardon me in advance. Above is my implementation of runtime mailer provider override as seen in the samples of this repo. However, this causes a CompilationError due to [object SMTPConfiguration is not a member of package play.api.libs.mailer]

My current version of mailer included in built.sbt is
> "com.typesafe.play" %% "play-mailer" % "3.0.1"
Is this class not included in the package as of that version?

Thank you for your help in advance.

**Comment by aekazitt** [comment]
Upgraded play-mailer to Milestone and problem disappears.

**Comment by Mogztter** [comment]
Hello @aekazitt, custom SMTPConfiguration providers were introduce in the latest milestone, that's why this is not working with version 3.0.1.

**Comment by aekazitt** [comment]
Please check out my implementation below:

    class MailerConfigProvider extends Provider[SMTPConfiguration]
        // Member Variables
        var host: String = "192.168.9.2"
        var port: Int = 25
        var sslEnabled: Boolean = false
        var tslEnabled: Boolean = false
        var debugMode: Boolean = false
        var mock: Boolean = true
        var user: Option[String] = Option.empty
        var pwd: Option[String] = Option.empty
        var connectionTimeout: Option[Int] = Option.empty
        var readTimeout: Option[Int] = Option.empty
    
        override deg get() =
            new SMTPConfiguration(host, port, sslEnabled, 
                        tslEnabled, user, pwd, debugMode, 
                        connectionTimeout, readTimeout, mock);
    
        // Getters - Setters
        def getHost(): String = host
        def setHost(host: String) { this.host = host }
        def getPort(): Int = port
        def setPort(port: Int) { this.port = port }
        def isSslEnabled(): Boolean = sslEnabled
        def setSslEnabled(ssl: Boolean) { this.sslEnabled = ssl }
        def isTslEnabled(): Boolean = tslEnabled
        def setTslEnabled(tsl: Boolean) { this.tslEnabled = tsl }
        ... & etc. 
    }
    class MailerConfigModule extends Module {
        def bindings(environment: Environment, configuration: Configuration) = Seq(
            bind[SMTPConfiguration].toProvider[MailerConfigProvider]
        )
    }

And I added the Module above into application.conf which now works fine with default settings. My next step is trying to change the default settings above with the included Getters and Setters when starting up the Server, or Changing user. All of the required information is saved inside the Schema.

How do you recommend I approach this? Ideally, I want to configure this SMTP setting inside a Job instance.

**Comment by Mogztter** [comment]
In your use case I think it's better to create a new instance: https://github.com/playframework/play-mailer/blob/master/user-manual.adoc#new-instances

If you really want to "provide" a `MailerConfigProvider` you can override the `get` function to create a `SMTPConfiguration` with the data read from your database:

```scala
override def get() = {
  val data = db.select(/* */)
  new SMTPConfiguration(data .host, data.port, data.sslEnabled, data.tslEnabled, data.user, data.pwd, data.debugMode, data.connectionTimeout, data.readTimeout, data.mock)
}
```

In Scala, I think it's better to use immutable objects (i.e. you should avoid using `var` and `getter`/`setter`)
